import type { Fragrance } from './types'

export const fragrances: Fragrance[] = [
  {
    id: 'sauvage-elixir',
    name: 'Sauvage',
    house: 'Dior',
    price: 195,
    concentration: 'Elixir',
    imageUrl: '/bottles/sauvage-elixir.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Grapefruit', 'Cinnamon', 'Nutmeg'],
    heartNotes: ['Lavender', 'Licorice'],
    baseNotes: ['Sandalwood', 'Amber', 'Patchouli'],
    rationale: 'A powerful, sophisticated evolution with warm spices perfect for evening elegance.',
    intensity: 5,
    longevity: '8-10 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'bleu-chanel',
    name: 'Bleu de Chanel',
    house: 'Chanel',
    price: 170,
    concentration: 'EDP',
    imageUrl: '/bottles/bleu-chanel.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Office', 'Formal'],
    season: ['Spring', 'Fall'],
    topNotes: ['Citrus', 'Grapefruit'],
    heartNotes: ['Ginger', 'Jasmine', 'Mint'],
    baseNotes: ['Cedar', 'Sandalwood', 'Amber'],
    rationale: 'Timeless sophistication with balanced projection, ideal for professional confidence.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'y-le-parfum',
    name: 'Y',
    house: 'YSL',
    price: 130,
    concentration: 'Parfum',
    imageUrl: '/bottles/y-le-parfum.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday', 'Date Night'],
    season: ['Spring', 'Summer'],
    topNotes: ['Apple', 'Ginger', 'Bergamot'],
    heartNotes: ['Sage', 'Lavender'],
    baseNotes: ['Tonka Bean', 'Cedar', 'Olibanum'],
    rationale: 'Modern and bold with fruity freshness balanced by warm woods for versatile wear.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'aventus',
    name: 'Aventus',
    house: 'Creed',
    price: 545,
    concentration: 'EDP',
    imageUrl: '/bottles/aventus.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Formal', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Pineapple', 'Bergamot', 'Apple'],
    heartNotes: ['Birch', 'Patchouli', 'Jasmine'],
    baseNotes: ['Oakmoss', 'Ambergris', 'Vanilla'],
    rationale: 'The iconic niche powerhouse combining fruity freshness with smoky depth.',
    intensity: 5,
    longevity: '8-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'light-blue',
    name: 'Light Blue',
    house: 'Dolce & Gabbana',
    price: 95,
    concentration: 'EDP',
    imageUrl: '/bottles/light-blue.jpg',
    family: ['Fresh', 'Floral'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Grapefruit', 'Mandarin'],
    heartNotes: ['Juniper', 'Sea Notes'],
    baseNotes: ['Musk', 'Amber'],
    rationale: 'Crisp Mediterranean freshness that remains approachable in warm weather.',
    intensity: 3,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'dg-pour-homme',
    name: 'Pour Homme',
    house: 'Dolce & Gabbana',
    price: 80,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Neroli', 'Petitgrain'],
    heartNotes: ['Tobacco', 'Geranium', 'Rosewood'],
    baseNotes: ['Tobacco', 'Musk', 'Amber'],
    rationale: 'The 1994 original that put D&G on the fragrance map — a warm, slightly smoky tobacco-neroli composition that remains a study in restrained Italian masculinity and is criminally underrated today.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'layton',
    name: 'Layton',
    house: 'Parfums de Marly',
    price: 320,
    concentration: 'EDP',
    imageUrl: '/bottles/dg-pour-homme.jpg',
    family: ['Woody', 'Floral'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Apple', 'Lavender', 'Mandarin'],
    heartNotes: ['Geranium', 'Jasmine', 'Violet'],
    baseNotes: ['Vanilla', 'Patchouli', 'Guaiac Wood'],
    rationale: 'Intoxicating sweetness with floral sophistication, a crowd-pleasing evening masterpiece.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'versace-eros',
    name: 'Eros',
    house: 'Versace',
    price: 85,
    concentration: 'EDT',
    imageUrl: '/bottles/versace-eros.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Mint', 'Lemon', 'Apple'],
    heartNotes: ['Tonka Bean', 'Ambroxan', 'Geranium'],
    baseNotes: ['Vanilla', 'Cedar', 'Oakmoss'],
    rationale: 'Youthful and vibrant with fresh mint opening and sweet dry-down for confident presence.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'versace-pour-homme',
    name: 'Pour Homme',
    house: 'Versace',
    price: 75,
    concentration: 'EDT',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Lemon', 'Neroli'],
    heartNotes: ['Clary Sage', 'Hyacinth', 'Cedar'],
    baseNotes: ['Tonka Bean', 'Musk', 'Amber'],
    rationale: 'A clean, Mediterranean fresh-woody that consistently outperforms its price point. Versatile, inoffensive, and frequently cited as one of the best entry-level designer masculines available.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'versace-eros-edp',
    name: 'Eros',
    house: 'Versace',
    price: 95,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Lemon', 'Bergamot', 'Apple'],
    heartNotes: ['Tonka Bean', 'Ambroxan', 'Vetiver'],
    baseNotes: ['Vanilla', 'Amber', 'Sandalwood'],
    rationale: 'The EDP takes the Eros formula and darkens it considerably — warmer, richer, and more seductive than the original with a stronger amber-vanilla drydown that lasts significantly longer.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'acqua-di-gio',
    name: 'Acqua di Giò',
    house: 'Giorgio Armani',
    price: 125,
    concentration: 'Profumo',
    imageUrl: '/bottles/acqua-di-gio.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Sea Notes'],
    heartNotes: ['Geranium', 'Rosemary', 'Sage'],
    baseNotes: ['Patchouli', 'Incense'],
    rationale: 'Refined aquatic freshness with aromatic depth, perfect for professional versatility.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'stronger-with-you',
    name: 'Stronger With You Intensely',
    house: 'Emporio Armani',
    price: 105,
    concentration: 'EDP',
    imageUrl: '/bottles/stronger-with-you.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Pink Pepper', 'Juniper'],
    heartNotes: ['Cinnamon', 'Lavender', 'Sage'],
    baseNotes: ['Tonka Bean', 'Vanilla', 'Amber'],
    rationale: 'Warm, inviting sweetness with spicy depth that creates intimate connection.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'terre-hermes',
    name: 'Terre d\'Hermès',
    house: 'Hermès',
    price: 175,
    concentration: 'EDT',
    imageUrl: '/bottles/terre-hermes.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Formal', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Grapefruit', 'Orange'],
    heartNotes: ['Pepper', 'Pelargonium'],
    baseNotes: ['Vetiver', 'Cedar', 'Patchouli'],
    rationale: 'Sophisticated earthiness with citrus brightness, the epitome of refined masculinity.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'spicebomb-extreme',
    name: 'Spicebomb Extreme',
    house: 'Viktor & Rolf',
    price: 120,
    concentration: 'EDP',
    imageUrl: '/bottles/spicebomb-extreme.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Black Pepper', 'Grapefruit'],
    heartNotes: ['Cinnamon', 'Saffron', 'Lavender'],
    baseNotes: ['Tobacco', 'Vanilla', 'Bourbon'],
    rationale: 'Explosive warmth with rich spices and tobacco, commanding attention in cold weather.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'tom-ford-oud',
    name: 'Oud Wood',
    house: 'Tom Ford',
    price: 290,
    concentration: 'EDP',
    imageUrl: '/bottles/tom-ford-oud.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Formal', 'Date Night'],
    season: ['Fall', 'Winter'],
    topNotes: ['Rosewood', 'Cardamom', 'Chinese Pepper'],
    heartNotes: ['Oud', 'Sandalwood', 'Vetiver'],
    baseNotes: ['Amber', 'Tonka Bean', 'Vanilla'],
    rationale: 'Smooth, approachable oud with velvety woods and subtle sweetness for sophisticated elegance.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'prada-lhomme',
    name: 'L\'Homme Prada',
    house: 'Prada',
    price: 115,
    concentration: 'EDT',
    imageUrl: '/bottles/prada-lhomme.jpg',
    family: ['Fresh', 'Amber'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Neroli', 'Black Pepper', 'Carrot Seeds'],
    heartNotes: ['Iris', 'Geranium', 'Mate'],
    baseNotes: ['Amber', 'Cedar', 'Patchouli'],
    rationale: 'Clean, powdery iris creates understated elegance perfect for refined modern professionals.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'the-one-edp',
    name: 'The One',
    house: 'Dolce & Gabbana',
    price: 110,
    concentration: 'EDP',
    imageUrl: '/bottles/the-one-edp.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Grapefruit', 'Coriander', 'Basil'],
    heartNotes: ['Ginger', 'Cardamom', 'Orange Blossom'],
    baseNotes: ['Amber', 'Tobacco', 'Cedar'],
    rationale: 'Seductive amber-tobacco blend with spicy warmth, perfect for intimate evening occasions.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'one-million',
    name: 'One Million',
    house: 'Paco Rabanne',
    price: 120,
    concentration: 'Parfum',
    imageUrl: '/bottles/one-million.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Blood Mandarin', 'Sage', 'Cardamom'],
    heartNotes: ['Rose', 'Cinnamon', 'Neroli'],
    baseNotes: ['Tonka Bean', 'Amber', 'Leather'],
    rationale: 'Bold, attention-grabbing sweetness with spicy leather undertones for confident statements.',
    intensity: 5,
    longevity: '8-10 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'givenchy-gentleman',
    name: 'Gentleman Réserve Privée',
    house: 'Givenchy',
    price: 135,
    concentration: 'EDP',
    imageUrl: '/bottles/givenchy-gentleman.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Whiskey', 'Cinnamon'],
    heartNotes: ['Iris', 'Orris'],
    baseNotes: ['Leather', 'Tonka Bean', 'Patchouli'],
    rationale: 'Refined whiskey-iris composition with smooth leather, embodying evening sophistication.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'valentino-uomo',
    name: 'Uomo',
    house: 'Valentino',
    price: 110,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Office', 'Everyday', 'Date Night'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Mandarin', 'Clary Sage'],
    heartNotes: ['Iris', 'Tonka Bean'],
    baseNotes: ['Vanilla', 'Leather', 'Amber'],
    rationale: 'Powdery iris meets creamy vanilla in a versatile, comforting signature scent.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'green-irish-tweed',
    name: 'Green Irish Tweed',
    house: 'Creed',
    price: 495,
    concentration: 'EDP',
    imageUrl: '/bottles/valentino-uomo.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday', 'Formal'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Lemon Verbena', 'Peppermint'],
    heartNotes: ['Violet Leaves', 'Iris'],
    baseNotes: ['Sandalwood', 'Ambergris'],
    rationale: 'Fresh, green elegance with a classic masculine edge, timeless and refined.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'tobacco-vanille',
    name: 'Tobacco Vanille',
    house: 'Tom Ford',
    price: 290,
    concentration: 'EDP',
    imageUrl: '/bottles/tobacco-vanille.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Tobacco Leaf', 'Spicy Notes'],
    heartNotes: ['Vanilla', 'Cocoa', 'Tonka Bean'],
    baseNotes: ['Dried Fruits', 'Woody Notes'],
    rationale: 'Decadent tobacco-vanilla pairing creates luxurious warmth for cold-weather evenings.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'mont-blanc-legend',
    name: 'Legend Spirit',
    house: 'Mont Blanc',
    price: 65,
    concentration: 'EDT',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer'],
    topNotes: ['Pink Pepper', 'Grapefruit', 'Bergamot'],
    heartNotes: ['Aquatic Notes', 'Lavender', 'Cardamom'],
    baseNotes: ['White Musk', 'Cashmere Wood', 'Oakmoss'],
    rationale: 'Fresh aquatic brightness with woody drydown, offering accessible everyday versatility.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'dior-homme-intense',
    name: 'Dior Homme',
    house: 'Dior',
    price: 155,
    concentration: 'EDP',
    imageUrl: '/bottles/mont-blanc-legend.jpg',
    family: ['Floral', 'Woody'],
    occasion: ['Office', 'Date Night', 'Formal'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Lavender', 'Sage', 'Bergamot'],
    heartNotes: ['Iris', 'Ambrette', 'Pear'],
    baseNotes: ['Cedar', 'Vetiver', 'Musk'],
    rationale: 'Powdery iris elegance with subtle lipstick accord, refined and distinctive.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'jpg-ultra-male',
    name: 'Ultra Male',
    house: 'Jean Paul Gaultier',
    price: 90,
    concentration: 'EDP',
    imageUrl: '/bottles/jpg-ultra-male.jpg',
    family: ['Amber', 'Fresh'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Pear', 'Bergamot', 'Black Lavender'],
    heartNotes: ['Mint', 'Cinnamon', 'Cumin'],
    baseNotes: ['Vanilla', 'Amber', 'Cedar'],
    rationale: 'Sweet, spicy powerhouse with fresh opening, polarizing but unforgettable.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'bvlgari-man',
    name: 'Man in Black',
    house: 'Bvlgari',
    price: 110,
    concentration: 'EDP',
    imageUrl: '/bottles/bvlgari-man.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Rum', 'Spices'],
    heartNotes: ['Iris', 'Tuberose', 'Leather'],
    baseNotes: ['Benzoin', 'Tonka Bean', 'Guaiac Wood'],
    rationale: 'Dark, mysterious composition with boozy spices and smooth leather depth.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'azzaro-wanted',
    name: 'The Most Wanted',
    house: 'Azzaro',
    price: 85,
    concentration: 'Parfum',
    imageUrl: '/bottles/azzaro-wanted.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Ginger', 'Red Ginger'],
    heartNotes: ['Toffee', 'Woody Notes'],
    baseNotes: ['Bourbon Vanilla', 'Tonka Bean', 'Caramel'],
    rationale: 'Sweet, gourmand warmth with spicy ginger kick, boldly modern and seductive.',
    intensity: 5,
    longevity: '8-10 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'azzaro-wanted-intense',
    name: 'The Most Wanted',
    house: 'Azzaro',
    price: 80,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cardamom', 'Ginger', 'Bergamot'],
    heartNotes: ['Toffee', 'Tobacco', 'Cedar'],
    baseNotes: ['Vanilla', 'Tonka Bean', 'Amber'],
    rationale: 'A spicier, smokier take on the Most Wanted DNA — cardamom and tobacco add depth and masculinity to the signature gourmand sweetness, making it the more complex and evening-focused sibling.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'burberry-london',
    name: 'London for Men',
    house: 'Burberry',
    price: 75,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Formal', 'Everyday'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Bergamot', 'Lavender', 'Cinnamon'],
    heartNotes: ['Mimosa', 'Leather', 'Port Wine'],
    baseNotes: ['Tobacco Leaf', 'Guaiac Wood', 'Oud'],
    rationale: 'Warm, gentlemanly tobacco-leather blend with boozy character, refined and classic.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'carolina-herrera',
    name: 'Bad Boy Cobalt',
    house: 'Carolina Herrera',
    price: 120,
    concentration: 'EDP',
    family: ['Amber', 'Fresh'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Pink Pepper', 'Plum'],
    heartNotes: ['Sage', 'Lavender'],
    baseNotes: ['Tonka Bean', 'Amber', 'Cedarwood'],
    rationale: 'Fresh spicy opening mellows into warm amber sweetness, youthful and versatile.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'chanel-allure-sport',
    name: 'Allure Homme Sport',
    house: 'Chanel',
    price: 160,
    concentration: 'Eau Extrême',
    imageUrl: '/bottles/azzaro-wanted-intense.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Mandarin', 'Mint', 'Cypress'],
    heartNotes: ['Pepper', 'Neroli', 'Cedar'],
    baseNotes: ['Tonka Bean', 'Musk', 'Sandalwood'],
    rationale: 'Athletic freshness with woody depth, energetic yet sophisticated for active lifestyles.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'pdm-pegasus',
    name: 'Pegasus',
    house: 'Parfums de Marly',
    price: 295,
    concentration: 'EDP',
    imageUrl: '/bottles/armaf-cdnim.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Heliotrope', 'Bergamot', 'Cumin'],
    heartNotes: ['Bitter Almond', 'Lavender', 'Jasmine'],
    baseNotes: ['Vanilla', 'Sandalwood', 'Amber'],
    rationale: 'Enchanting almond-vanilla sweetness with aromatic depth, beloved for its crowd-pleasing warmth.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'versace-dylan-blue',
    name: 'Dylan Blue',
    house: 'Versace',
    price: 80,
    concentration: 'EDT',
    imageUrl: '/bottles/versace-dylan-blue.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Grapefruit', 'Fig Leaves', 'Bergamot'],
    heartNotes: ['Violet Leaves', 'Papyrus', 'Black Pepper'],
    baseNotes: ['Musk', 'Tonka Bean', 'Incense'],
    rationale: 'Fresh aquatic with woody depth and subtle incense, a versatile modern classic.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'creed-aventus-cologne',
    name: 'Aventus',
    house: 'Creed',
    price: 430,
    concentration: 'EDC',
    imageUrl: '/bottles/creed-aventus-cologne.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer'],
    topNotes: ['Mandarin', 'Ginger', 'Pink Pepper'],
    heartNotes: ['Patchouli', 'Vetiver', 'Sandalwood'],
    baseNotes: ['Birch', 'Musk', 'Styrax'],
    rationale: 'Fresher interpretation of Aventus with citrus brightness, perfect for warmer weather.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'ysl-lhomme',
    name: 'L\'Homme Ultime',
    house: 'YSL',
    price: 130,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Date Night', 'Formal'],
    season: ['Spring', 'Fall', 'Winter'],
    topNotes: ['Mint', 'Lavender', 'Bergamot'],
    heartNotes: ['Geranium', 'Vetiver'],
    baseNotes: ['Tonka Bean', 'Cedar', 'Patchouli'],
    rationale: 'Sophisticated fresh aromatic with warm woody base, refined and versatile for modern gentlemen.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'amouage-interlude',
    name: 'Interlude Man',
    house: 'Amouage',
    price: 380,
    concentration: 'EDP',
    imageUrl: '/bottles/ysl-lhomme.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Formal', 'Date Night'],
    season: ['Fall', 'Winter'],
    topNotes: ['Oregano', 'Pepper', 'Bergamot'],
    heartNotes: ['Amber', 'Incense', 'Opoponax'],
    baseNotes: ['Leather', 'Agarwood', 'Patchouli'],
    rationale: 'Complex, resinous masterpiece with smoky incense and leather, bold niche artistry.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'xerjoff-naxos',
    name: 'Naxos',
    house: 'Xerjoff',
    price: 295,
    concentration: 'EDP',
    imageUrl: '/bottles/xerjoff-naxos.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Lavender', 'Bergamot', 'Lemon'],
    heartNotes: ['Honey', 'Cinnamon', 'Jasmine'],
    baseNotes: ['Tobacco', 'Vanilla', 'Tonka Bean'],
    rationale: 'Luxurious honey-tobacco blend with aromatic lavender, exquisitely crafted sweetness.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'hermessence-vetiver-tonka',
    name: 'Vétiver Tonka',
    house: 'Hermès',
    price: 220,
    concentration: 'EDP',
    imageUrl: '/bottles/memo-irish-leather.jpg',
    family: ['Woody'],
    occasion: ['Office', 'Everyday', 'Formal'],
    season: ['Spring', 'Summer', 'Fall', 'Winter'],
    topNotes: ['Vetiver'],
    heartNotes: ['Tonka Bean'],
    baseNotes: ['Cedarwood', 'Oakmoss'],
    rationale: 'Minimalist elegance pairing earthy vetiver with creamy tonka, timeless sophistication.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'frederic-malle-musc-ravageur',
    name: 'Musc Ravageur',
    house: 'Frédéric Malle',
    price: 295,
    concentration: 'EDP',
    imageUrl: '/bottles/frederic-malle-musc-ravageur.jpg',
    family: ['Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Tangerine', 'Lavender'],
    heartNotes: ['Musk', 'Cinnamon', 'Clove'],
    baseNotes: ['Vanilla', 'Amber', 'Sandalwood'],
    rationale: 'Opulent, sensual musk with warm spices and vanilla, intimate and captivating.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'prada-lhomme-intense',
    name: 'L\'Homme Prada Intense',
    house: 'Prada',
    price: 125,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Office', 'Date Night', 'Formal'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Iris', 'Neroli'],
    heartNotes: ['Amber', 'Tonka Bean', 'Patchouli'],
    baseNotes: ['Sandalwood', 'Leather'],
    rationale: 'Powdery iris meets warm amber and tonka, sophisticated warmth with refined character.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'dior-eau-sauvage',
    name: 'Eau Sauvage',
    house: 'Dior',
    price: 130,
    concentration: 'EDT',
    family: ['Fresh'],
    occasion: ['Everyday', 'Office', 'Formal'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Lemon', 'Rosemary'],
    heartNotes: ['Hedione', 'Jasmine', 'Iris'],
    baseNotes: ['Oakmoss', 'Vetiver', 'Musk'],
    rationale: 'The 1966 original that invented modern masculinity. First use of hedione gave it an airy, almost supernatural freshness that still feels contemporary today.',
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'guerlain-vetiver',
    name: 'Vetiver',
    house: 'Guerlain',
    price: 120,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Formal', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Lemon', 'Bergamot', 'Coriander'],
    heartNotes: ['Tobacco', 'Nutmeg', 'Pepper'],
    baseNotes: ['Vetiver', 'Cedar', 'Oakmoss'],
    rationale: 'The 1961 benchmark that defined vetiver in fine fragrance. Earthy, green, and smoky — a masterclass in understated masculine elegance.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'ysl-kouros',
    name: 'Kouros',
    house: 'YSL',
    price: 80,
    concentration: 'EDT',
    family: ['Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Aldehydes', 'Bergamot', 'Coriander'],
    heartNotes: ['Civet', 'Leather', 'Patchouli'],
    baseNotes: ['Oakmoss', 'Vanilla', 'Musk'],
    rationale: 'Sweaty, animalic, and daring — Kouros rewrote the rules of masculinity in 1981. A polarizing benchmark every fragrance lover must smell at least once.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'guerlain-habit-rouge',
    name: 'Habit Rouge',
    house: 'Guerlain',
    price: 115,
    concentration: 'EDT',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Lemon', 'Neroli'],
    heartNotes: ['Carnation', 'Cinnamon', 'Rose'],
    baseNotes: ['Rum', 'Leather', 'Vanilla'],
    rationale: 'The 1965 pioneer of oriental masculinity. A warm, spiced-citrus composition of extraordinary elegance that still has no true rival.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'drakkar-noir',
    name: 'Drakkar Noir',
    house: 'Guy Laroche',
    price: 45,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Lemon', 'Bergamot', 'Lavender'],
    heartNotes: ['Juniper', 'Coriander', 'Artemisia'],
    baseNotes: ['Cedarwood', 'Pine', 'Musk'],
    rationale: 'The defining fougère of the 1980s. Its spicy-lavender swagger dominated an era and still smells powerfully distinct — essential fragrance history.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'polo-green',
    name: 'Polo Green',
    house: 'Ralph Lauren',
    price: 60,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Pine', 'Basil', 'Citrus'],
    heartNotes: ['Leather', 'Tobacco', 'Coriander'],
    baseNotes: ['Patchouli', 'Oakmoss', 'Vetiver'],
    rationale: 'A distinctly American icon from 1978. Bold, green, and outdoorsy with leather and oakmoss — foundational to understanding the chypre family.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'davidoff-cool-water',
    name: 'Cool Water',
    house: 'Davidoff',
    price: 50,
    concentration: 'EDT',
    family: ['Fresh'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Dihydromyrcenol', 'Mint', 'Lavender'],
    heartNotes: ['Geranium', 'Rosemary', 'Sandalwood'],
    baseNotes: ['Musk', 'Amber', 'Oakmoss'],
    rationale: 'The 1988 aquatic that launched a thousand imitators. Understanding Cool Water is understanding the entire fresh-aquatic genre that dominated the 1990s.',
    intensity: 3,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'dior-fahrenheit',
    name: 'Fahrenheit',
    house: 'Dior',
    price: 140,
    concentration: 'EDT',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Violet', 'Mandarin', 'Hawthorn'],
    heartNotes: ['Leather', 'Nutmeg', 'Gasoline Accord'],
    baseNotes: ['Vetiver', 'Cedar', 'Musk'],
    rationale: 'A 1988 avant-garde masterpiece — violet, gasoline, and leather in impossible harmony. Nothing smells like it. A mandatory experience for any fragrance enthusiast.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'aramis-classic',
    name: 'Aramis',
    house: 'Aramis',
    price: 55,
    concentration: 'EDT',
    family: ['Woody', 'Amber'],
    occasion: ['Office', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Aldehydes', 'Artemisia', 'Bergamot'],
    heartNotes: ['Leather', 'Patchouli', 'Vetiver'],
    baseNotes: ['Oakmoss', 'Amber', 'Musk'],
    rationale: 'The 1966 leather-chypre that shaped American masculine perfumery. A cornerstone of fragrance history — dark, animalic, and utterly confident.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'givenchy-gentleman-original',
    name: 'Gentleman (Original 1974)',
    house: 'Givenchy',
    price: 95,
    concentration: 'EDT',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cinnamon', 'Honey', 'Aldehydes'],
    heartNotes: ['Patchouli', 'Civet', 'Orris'],
    baseNotes: ['Oakmoss', 'Leather', 'Vetiver'],
    rationale: 'Simultaneously carnal and edible — animalic civet, sweet honey, and dank patchouli in perfect tension. A masterpiece that the 2018 reboot cannot fully replace.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  // ── MODERN DESIGNER ICONS ────────────────────────────────────────────────
  {
    id: 'terre-hermes-parfum',
    name: 'Terre d\'Hermès Parfum',
    house: 'Hermès',
    price: 195,
    concentration: 'Parfum',
    family: ['Woody', 'Amber'],
    occasion: ['Office', 'Formal', 'Date Night'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Grapefruit', 'Pepper'],
    heartNotes: ['Vetiver', 'Flint'],
    baseNotes: ['Benzoin', 'Cedar', 'Patchouli'],
    rationale: 'The deeper, richer parfum concentration of the iconic Terre d\'Hermès. More resinous and earthy, moving closer to pure mineral-citrus perfection.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'bleu-chanel-parfum',
    name: 'Bleu de Chanel',
    house: 'Chanel',
    price: 195,
    concentration: 'Parfum',
    family: ['Woody', 'Amber'],
    occasion: ['Office', 'Formal', 'Date Night'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Citrus', 'Grapefruit', 'Mint'],
    heartNotes: ['Ginger', 'Nutmeg', 'Jasmine'],
    baseNotes: ['Labdanum', 'Sandalwood', 'Vetiver'],
    rationale: 'The finest iteration of the Bleu line — deeper labdanum and sandalwood base lifts it from mass-market into something genuinely luxurious and complex.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'jpg-le-male',
    name: 'Le Male',
    house: 'Jean Paul Gaultier',
    price: 75,
    concentration: 'EDT',
    family: ['Fresh', 'Amber'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Mint', 'Lavender', 'Bergamot'],
    heartNotes: ['Cumin', 'Cinnamon', 'Orange Blossom'],
    baseNotes: ['Vanilla', 'Sandalwood', 'Amber'],
    rationale: 'The 1995 icon that defined a generation. Lavender-vanilla-mint in a sailor torso bottle — seductive, approachable, and still influential on men\'s fragrance today.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'acqua-di-gio-original',
    name: 'Acqua di Giò',
    house: 'Giorgio Armani',
    price: 85,
    concentration: 'EDT',
    family: ['Fresh'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Neroli', 'Green Tangerine'],
    heartNotes: ['Jasmine', 'Calone', 'Persimmon'],
    baseNotes: ['Cedar', 'Patchouli', 'Musk'],
    rationale: 'The world\'s best-selling men\'s fragrance for decades. Its jasmine-calone marine freshness set the blueprint for an entire generation of summer colognes.',
    intensity: 3,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'dior-homme-parfum',
    name: 'Dior Homme',
    house: 'Dior',
    price: 175,
    concentration: 'Parfum',
    family: ['Floral', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Iris'],
    heartNotes: ['Rose', 'Iris Absolute', 'Chocolate'],
    baseNotes: ['Smoked Vetiver', 'Leather', 'Incense'],
    rationale: 'A polarizing 2014 masterwork — iris, rose, and chocolate over a smoky leather base. Considered by many connoisseurs to be the finest Dior Homme expression.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'jpg-le-male-le-parfum',
    name: 'Le Male',
    house: 'Jean Paul Gaultier',
    price: 110,
    concentration: 'Parfum',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cardamom', 'Lavender', 'Mint'],
    heartNotes: ['Iris', 'Orange Blossom'],
    baseNotes: ['Vanilla', 'Sandalwood', 'Tonka Bean'],
    rationale: 'The mature, luxurious evolution of Le Male — deeper cardamom and vanilla intensity, with Fragrantica naming it among the best men\'s fragrances of all time.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'issey-miyake-leau',
    name: 'L\'Eau d\'Issey Pour Homme',
    house: 'Issey Miyake',
    price: 80,
    concentration: 'EDT',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Yuzu', 'Mandarin', 'Verbena'],
    heartNotes: ['Cinnamon', 'Nutmeg', 'Saffron'],
    baseNotes: ['Sandalwood', 'Vetiver', 'Musk'],
    rationale: 'A 1994 revolution — the first true aquatic-woody masculine, with a watery yuzu clarity that changed the direction of men\'s perfumery permanently.',
    intensity: 3,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'hugo-boss-bottled',
    name: 'Boss Bottled',
    house: 'Hugo Boss',
    price: 75,
    concentration: 'EDT',
    family: ['Woody', 'Amber'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Fall'],
    topNotes: ['Apple', 'Plum', 'Citrus'],
    heartNotes: ['Cinnamon', 'Geranium', 'Mahogany'],
    baseNotes: ['Sandalwood', 'Vanilla', 'Vetiver'],
    rationale: 'The 1998 apple-spice-sandalwood blueprint that shaped a decade of men\'s fragrance. Groundbreaking in its approachability — and still the best at what it does.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'hugo-boss-bottled-absolu',
    name: 'Boss Bottled Absolu',
    house: 'Hugo Boss',
    price: 95,
    concentration: 'Parfum',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cardamom', 'Ginger', 'Bergamot'],
    heartNotes: ['Vetiver', 'Geranium', 'Cedarwood'],
    baseNotes: ['Benzyl Benzoate', 'Amber', 'Musk'],
    rationale: 'The richest, most seductive Boss Bottled to date — warm cardamom and amber give the classic DNA a darker, more sophisticated edge. A significant upgrade for evening wear.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'hugo-boss-cologne',
    name: 'Hugo Man',
    house: 'Hugo Boss',
    price: 65,
    concentration: 'EDT',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Apple', 'Citrus'],
    heartNotes: ['Geranium', 'Lavender', 'Cinnamon'],
    baseNotes: ['Sandalwood', 'Oakmoss', 'Musk'],
    rationale: 'The clean, accessible blue-bottle classic that introduced countless men to designer fragrance. Fresh citrus-lavender simplicity done reliably well at an honest price.',
    intensity: 3,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'stetson-classic',
    name: 'Stetson Classic',
    house: 'Coty',
    price: 20,
    concentration: 'Cologne',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Lemon', 'Aldehydes'],
    heartNotes: ['Geranium', 'Oakmoss', 'Spices'],
    baseNotes: ['Sandalwood', 'Musk', 'Amber'],
    rationale: 'A 1981 American classic that punches well above its drugstore price. Woody, clean, and unpretentious — a reminder that great fragrance doesn\'t require a luxury price tag.',
    intensity: 3,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'paco-1-million-original',
    name: '1 Million',
    house: 'Paco Rabanne',
    price: 95,
    concentration: 'EDT',
    imageUrl: '/bottles/parfums-de-nicolai-new-york.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Grapefruit', 'Blood Mandarin', 'Peppermint'],
    heartNotes: ['Rose', 'Cinnamon', 'Spices'],
    baseNotes: ['Leather', 'Amber', 'Patchouli'],
    rationale: 'An unapologetically bold sweet-leather statement that became a global phenomenon. Love it or hate it, this 2008 release is impossible to ignore or forget.',
    intensity: 5,
    longevity: '8-10 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'ysl-la-nuit',
    name: 'La Nuit de L\'Homme',
    house: 'YSL',
    price: 100,
    concentration: 'EDT',
    imageUrl: '/bottles/ysl-la-nuit.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cardamom', 'Bergamot'],
    heartNotes: ['Lavender', 'Cedar', 'Caraway'],
    baseNotes: ['Vetiver', 'Coumarin', 'Sandalwood'],
    rationale: 'The 2009 cardamom-cedar seduction that redefined "date night" fragrance for an entire generation. Three perfumers collaborated to create this singular achievement.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'ysl-myslf',
    name: 'MYSLF',
    house: 'YSL',
    price: 130,
    concentration: 'EDP',
    imageUrl: '/bottles/ysl-myslf.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Orange Blossom', 'Grapefruit'],
    heartNotes: ['Ambroxan', 'Cedarwood', 'Cardamom'],
    baseNotes: ['Sandalwood', 'Vetiver', 'Musk'],
    rationale: 'YSL\'s most acclaimed masculine release in years — a radiant orange blossom-ambroxan-cedar composition that balances freshness and warmth with effortless versatility. Fragrantica 2024 award winner.',
    intensity: 3,
    longevity: '7-9 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'dior-sauvage-edt',
    name: 'Sauvage',
    house: 'Dior',
    price: 135,
    concentration: 'EDT',
    imageUrl: '/bottles/dior-sauvage-edt.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Pepper'],
    heartNotes: ['Lavender', 'Pink Pepper', 'Geranium'],
    baseNotes: ['Ambroxan', 'Cedar', 'Vetiver'],
    rationale: 'The world\'s best-selling fragrance — a bottle sells every three seconds globally. Its bergamot-ambroxan freshness is the definitive entry point into modern masculinity and an essential reference for any collection.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'dior-sauvage-edp',
    name: 'Sauvage',
    house: 'Dior',
    price: 155,
    concentration: 'EDP',
    imageUrl: '/bottles/dior-sauvage-edp.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Sichuan Pepper'],
    heartNotes: ['Lavender', 'Pink Pepper', 'Vetiver'],
    baseNotes: ['Ambroxan', 'Vanilla', 'Patchouli'],
    rationale: 'The best-selling fragrance in the world. Its ambroxan-lavender skin-scent quality has a near-universal appeal that makes it an essential reference point.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'chanel-allure-sport-original',
    name: 'Allure Homme Sport',
    house: 'Chanel',
    price: 150,
    concentration: 'EDT',
    imageUrl: '/bottles/chanel-allure-sport-original.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Citrus', 'Aldehydes', 'Grapefruit'],
    heartNotes: ['Spices', 'Tonka Bean', 'Cedar'],
    baseNotes: ['White Musk', 'Vetiver', 'Sandalwood'],
    rationale: 'Jacques Polge\'s 2004 feat of making a fresh sport fragrance genuinely sexy. A masterclass in contradiction — sporty yet sophisticated, with bags of sex appeal.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  // ── NICHE & PRESTIGE ─────────────────────────────────────────────────────
  {
    id: 'pdm-althaïr',
    name: 'Althaïr',
    house: 'Parfums de Marly',
    price: 320,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Cardamom'],
    heartNotes: ['Iris', 'Orris', 'Rose'],
    baseNotes: ['Vanilla', 'Amber', 'Tonka Bean', 'Musk'],
    rationale: 'PdM\'s most elegant creation — a powdery vanilla-iris warmth that was voted among women\'s favorite men\'s fragrances at the Fragrantica Community Awards.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'fm-portrait-of-a-lady',
    name: 'Portrait of a Lady',
    house: 'Frédéric Malle',
    price: 310,
    concentration: 'EDP',
    imageUrl: '/bottles/pdm-althaïr.jpg',
    family: ['Floral', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Turkish Rose', 'Blackcurrant', 'Raspberry'],
    heartNotes: ['Patchouli', 'Geranium', 'Incense'],
    baseNotes: ['Sandalwood', 'Musk', 'Amber'],
    rationale: 'Technically unisex but commonly worn by men who appreciate its stunning rose-patchouli architecture. One of the most critically acclaimed fragrances of the modern era.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'xerjoff-erba-pura',
    name: 'Erba Pura',
    house: 'Xerjoff',
    price: 245,
    concentration: 'EDP',
    imageUrl: '/bottles/xerjoff-erba-pura.jpg',
    family: ['Fresh', 'Amber'],
    occasion: ['Everyday', 'Date Night'],
    season: ['Spring', 'Summer'],
    topNotes: ['Sicilian Lemon', 'Calabrian Bergamot', 'Mango'],
    heartNotes: ['White Flowers', 'Fruity Notes'],
    baseNotes: ['Amberwood', 'White Musk', 'Sandalwood'],
    rationale: 'A sunshine-in-a-bottle citrus-fruity-amber that gets universal compliments. Carefree and joyful, with extraordinary longevity for its genre.',
    intensity: 4,
    longevity: '8-12 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'amouage-reflection-man',
    name: 'Reflection Man',
    house: 'Amouage',
    price: 360,
    concentration: 'EDP',
    imageUrl: '/bottles/amouage-reflection-man.jpg',
    family: ['Floral', 'Woody'],
    occasion: ['Office', 'Everyday', 'Formal'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Neroli', 'Rosemary', 'Lemon'],
    heartNotes: ['Iris', 'Jasmine', 'Rose'],
    baseNotes: ['Sandalwood', 'Musk', 'Amber'],
    rationale: 'Amouage\'s most wearable masterpiece — a refined neroli-iris-sandalwood that proves grand perfumery doesn\'t require aggression. Effortlessly aristocratic.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'amouage-jubilation-xxv',
    name: 'Jubilation XXV Man',
    house: 'Amouage',
    price: 395,
    concentration: 'EDP',
    imageUrl: '/bottles/amouage-jubilation-xxv.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Formal', 'Date Night'],
    season: ['Fall', 'Winter'],
    topNotes: ['Frankincense', 'Cardamom', 'Myrrh'],
    heartNotes: ['Oud', 'Rose', 'Patchouli'],
    baseNotes: ['Labdanum', 'Sandalwood', 'Cistus'],
    rationale: 'Grand ceremonial perfumery at its absolute peak — frankincense, oud, and rose in majestic proportion. A once-in-a-lifetime fragrance experience.',
    intensity: 5,
    longevity: '12+ hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'tom-ford-neroli-portofino',
    name: 'Neroli Portofino',
    house: 'Tom Ford',
    price: 290,
    concentration: 'EDT',
    imageUrl: '/bottles/tom-ford-neroli-portofino.jpg',
    family: ['Fresh', 'Floral'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Mandarin', 'Lemon'],
    heartNotes: ['Neroli', 'Lavender', 'Rosemary'],
    baseNotes: ['Amber', 'Oakmoss', 'Angelica'],
    rationale: 'The definitive luxury Italian summer fragrance — a turquoise-bottle icon that transports you to the Ligurian coast. Sets the standard for high-end citrus-neroli.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'amouage-decision',
    name: 'Decision',
    house: 'Amouage',
    price: 375,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Office', 'Formal', 'Date Night'],
    season: ['Spring', 'Fall', 'Winter'],
    topNotes: ['Bergamot', 'Juniper Berries'],
    heartNotes: ['Frankincense', 'Myrrh', 'Geranium'],
    baseNotes: ['Cedarwood', 'Vanilla', 'Patchouli'],
    rationale: 'Robb Report\'s #1 greatest men\'s cologne of 2025 — a resinous, sweet, aromatic masterwork by Quentin Bisch with mass appeal unprecedented for Amouage.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'jpg-le-male-elixir',
    name: 'Le Male',
    house: 'Jean Paul Gaultier',
    price: 130,
    concentration: 'Elixir',
    imageUrl: '/bottles/amouage-decision.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Lavender', 'Cardamom', 'Mint'],
    heartNotes: ['Vanilla', 'Hawthorn', 'Iris'],
    baseNotes: ['Tonka Bean', 'Amber', 'Sandalwood'],
    rationale: 'The richest, most opulent Le Male to date — a warm amber-lavender-vanilla concentration that turns the iconic DNA into something worthy of a luxury house.',
    intensity: 5,
    longevity: '10-12 hrs',
    sillage: 'Very Strong',
    projection: 5,
  },
  {
    id: 'jpg-le-beau',
    name: 'Le Beau',
    house: 'Jean Paul Gaultier',
    price: 95,
    concentration: 'EDT',
    imageUrl: '/bottles/jpg-le-beau.jpg',
    family: ['Fresh', 'Amber'],
    occasion: ['Everyday', 'Date Night'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Coconut', 'Grapefruit'],
    heartNotes: ['Vetiver', 'Iris'],
    baseNotes: ['Tonka Bean', 'Amber', 'Vanilla'],
    rationale: 'A tropical, solar take on the Le Male universe — coconut brightness over warm tonka creates a seductive summer masculine that punches well above its price.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'azzaro-pour-homme',
    name: 'Azzaro Pour Homme',
    house: 'Azzaro',
    price: 55,
    concentration: 'EDT',
    imageUrl: '/bottles/azzaro-pour-homme.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Anise', 'Basil', 'Bergamot'],
    heartNotes: ['Oakmoss', 'Clary Sage', 'Geranium'],
    baseNotes: ['Vetiver', 'Tonka Bean', 'Cedar'],
    rationale: 'The 1978 aromatic fougère that defined a genre. Anise-basil freshness over mossy warmth — a stone-cold classic studied by every perfumer and loved by their grandfathers.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'azzaro-chrome',
    name: 'Chrome',
    house: 'Azzaro',
    price: 60,
    concentration: 'EDT',
    imageUrl: '/bottles/azzaro-chrome.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Lemon', 'Pineapple'],
    heartNotes: ['Coriander', 'Oakmoss', 'Rosemary'],
    baseNotes: ['Tonka Bean', 'Sandalwood', 'Cedar'],
    rationale: 'A 1996 fresh aromatic that became one of Europe\'s best-selling masculines — clean, bright, and universally inoffensive in the best possible way. The definition of crowd-pleasing.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'polo-blue-edp',
    name: 'Polo Blue',
    house: 'Ralph Lauren',
    price: 85,
    concentration: 'EDP',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Cantaloupe', 'Cucumber', 'Sage'],
    heartNotes: ['Basil', 'Suede'],
    baseNotes: ['Vetiver', 'Patchouli', 'Musk'],
    rationale: 'The EDP takes the aquatic-melon freshness of the original and grounds it with a suede-vetiver base — more complex, longer-lasting, and universally praised as the superior version.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'paco-rabanne-pour-homme',
    name: 'Paco Rabanne Pour Homme',
    house: 'Paco Rabanne',
    price: 65,
    concentration: 'EDT',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Rosemary', 'Basil', 'Bergamot'],
    heartNotes: ['Oakmoss', 'Geranium', 'Clary Sage'],
    baseNotes: ['Vetiver', 'Labdanum', 'Tonka Bean'],
    rationale: 'The 1973 aromatic fougère alongside Azzaro Pour Homme as foundational masculine perfumery. Herbal, mossy, and unmistakably masculine — essential fragrance history.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'paco-invictus-edp',
    name: 'Invictus',
    house: 'Paco Rabanne',
    price: 110,
    concentration: 'EDP',
    imageUrl: '/bottles/polo-blue-edp.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Grapefruit', 'Sea Notes', 'Bay Laurel'],
    heartNotes: ['Hedione', 'Jasmine'],
    baseNotes: ['Guaiac Wood', 'Patchouli', 'Oakmoss'],
    rationale: 'One of the best-selling masculines globally — a clean, sporty aquatic with a woody drydown that strikes the perfect balance between fresh and warm. Universally liked.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'paco-phantom',
    name: 'Phantom',
    house: 'Paco Rabanne',
    price: 105,
    concentration: 'EDT',
    family: ['Amber', 'Fresh'],
    occasion: ['Everyday', 'Date Night'],
    season: ['Fall', 'Winter'],
    topNotes: ['Lemon', 'Lavender', 'Robot Head'],
    heartNotes: ['Vetiver', 'Vanilla'],
    baseNotes: ['Woody Notes', 'Musk', 'Mineral'],
    rationale: 'A 2021 standout in a sea of safe releases — lemon-lavender freshness pivots into a warm vanilla-vetiver base with surprising depth. The futuristic robot bottle is just a bonus.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'versace-eros-energy',
    name: 'Eros Energy',
    house: 'Versace',
    price: 95,
    concentration: 'EDP',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Lemon', 'Bergamot', 'Apple'],
    heartNotes: ['Mint', 'Geranium', 'Black Pepper'],
    baseNotes: ['Sandalwood', 'Musk', 'Amber'],
    rationale: 'A crisper, more energetic take on the Eros line — citrus-mint freshness with a clean woody base makes it the most versatile and office-appropriate entry in the Eros family.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'valentino-born-in-roma-intense',
    name: 'Born In Roma Uomo Intense',
    house: 'Valentino',
    price: 130,
    concentration: 'EDP',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Black Pepper', 'Cardamom'],
    heartNotes: ['Vetiver', 'Hawthorn', 'Leather'],
    baseNotes: ['Tonka Bean', 'Vanilla', 'Iso E Super'],
    rationale: 'A brooding, intensified take on Born In Roma — black pepper and leather give it an edge the original lacks, making it one of Valentino\'s most compelling masculine releases.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'prada-paradigme',
    name: 'Paradoxe Pour Homme',
    house: 'Prada',
    price: 135,
    concentration: 'EDP',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Neroli', 'Mandarin'],
    heartNotes: ['Iris', 'Vetiver', 'Patchouli'],
    baseNotes: ['Sandalwood', 'Amber', 'Musk'],
    rationale: 'Prada\'s 2023 masculine statement — a refined iris-vetiver-sandalwood composition that sits confidently between fresh and warm. Polished, modern, and broadly wearable.',
    intensity: 3,
    longevity: '7-9 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'prada-luna-rossa-black',
    name: 'Luna Rossa Black',
    house: 'Prada',
    price: 115,
    concentration: 'EDP',
    imageUrl: '/bottles/paco-phantom.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Iris', 'Angelica'],
    heartNotes: ['Ambroxan', 'Labdanum'],
    baseNotes: ['Patchouli', 'Coumarin', 'Musk'],
    rationale: 'A sleek, modern take on the Luna Rossa line — iris and ambroxan create a cool, skin-close sensuality over a warm patchouli base. One of Prada\'s most seductive and underrated masculines.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'jo-malone-wood-sage-sea-salt',
    name: 'Wood Sage & Sea Salt',
    house: 'Jo Malone',
    price: 165,
    concentration: 'Cologne',
    imageUrl: '/bottles/jo-malone-wood-sage-sea-salt.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Sea Salt', 'Ambrette'],
    heartNotes: ['Sage', 'Driftwood'],
    baseNotes: ['Mineral Notes', 'Musk'],
    rationale: 'Jo Malone\'s most beloved cologne — a coastal, mineral freshness that manages to smell both effortless and expensive. The gold standard for understated summer luxury.',
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'gucci-guilty-edp',
    name: 'Guilty Eau de Parfum Pour Homme',
    house: 'Gucci',
    price: 115,
    concentration: 'EDP',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Lemon', 'Lavender', 'Orange'],
    heartNotes: ['Neroli', 'Cedar', 'Patchouli'],
    baseNotes: ['Vetiver', 'Amber', 'Musk'],
    rationale: 'A warm, confident lavender-patchouli-amber that strikes a perfect balance between approachable and sophisticated. One of Gucci\'s most consistently praised masculine releases.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'pdm-perseus',
    name: 'Perseus',
    house: 'Parfums de Marly',
    price: 320,
    concentration: 'EDP',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Grapefruit', 'Elemi'],
    heartNotes: ['Cardamom', 'Vetiver', 'Patchouli'],
    baseNotes: ['Sandalwood', 'Amber', 'Musk'],
    rationale: 'A masterclass in fresh-woody balance from PdM — citrus brightness gives way to a cardamom-vetiver heart before landing on a warm sandalwood base. Versatile enough for any occasion.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'mercedes-benz-club-black-edt',
    name: 'Club Black',
    house: 'Mercedes-Benz',
    price: 45,
    concentration: 'EDT',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot'],
    heartNotes: ['Incense', 'Jasmine'],
    baseNotes: ['Vanilla', 'Benzoin', 'Ambroxan', 'Woodsy Notes'],
    rationale: 'The fragrance community\'s best-kept secret — a dark, smoky vanilla-benzoin that punches absurdly above its price point. Rich, masculine, and cozy without being cloying. Widely regarded as one of the best value vanilla fragrances ever made.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'mercedes-benz-club-black-edp',
    name: 'Club Black',
    house: 'Mercedes-Benz',
    price: 60,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Vanilla'],
    heartNotes: ['Jasmine', 'Myrrh', 'Incense'],
    baseNotes: ['Elemi Resin', 'Vanilla', 'Woody Notes'],
    rationale: 'The 2025 EDP evolution of the beloved Club Black — spicier and more resinous than the EDT, with myrrh and elemi lending an oriental depth. More mature and woody, while retaining the signature vanilla-benzoin DNA that made the original iconic.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'montblanc-legend-edt',
    name: 'Legend',
    house: 'Montblanc',
    price: 55,
    concentration: 'EDT',
    imageUrl: '/bottles/gucci-guilty-edp.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Lavender', 'Pineapple Leaf', 'Verbena'],
    heartNotes: ['Oakmoss', 'Geranium', 'Coumarin', 'Apple', 'Rose'],
    baseNotes: ['Sandalwood', 'Tonka Bean', 'Evernyl'],
    rationale: 'The definitive entry-level aromatic fougère — a fresh, approachable masculine that works in any context and any season. Its clean pineapple-lavender DNA has made it one of the best-selling and most recommended "safe blind buys" in the fragrance world.',
    intensity: 2,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'montblanc-legend-edp',
    name: 'Legend',
    house: 'Montblanc',
    price: 70,
    concentration: 'EDP',
    imageUrl: '/bottles/montblanc-legend-edp.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Date Night', 'Everyday'],
    season: ['Spring', 'Fall', 'Winter'],
    topNotes: ['Violet Leaves', 'Bergamot'],
    heartNotes: ['Oakmoss', 'Jasmine', 'Cedar'],
    baseNotes: ['Sandalwood', 'Tonka Bean', 'Musk'],
    rationale: 'The richer, more complex sibling of Legend EDT — violet leaves and jasmine give it a distinctly floral-woody character that feels more sophisticated and mature. Outstanding performer for the price with near-universal compliment appeal.',
    intensity: 3,
    longevity: '8-10 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'montblanc-legend-night',
    name: 'Legend Night',
    house: 'Montblanc',
    price: 65,
    concentration: 'EDP',
    imageUrl: '/bottles/montblanc-legend-night.jpg',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cardamom', 'Mint', 'Clary Sage', 'Bergamot'],
    heartNotes: ['Apple', 'Lavender', 'Cedar', 'Violet', 'Fir Resin'],
    baseNotes: ['Black Vanilla Husk', 'Akigalawood', 'Musk', 'Patchouli', 'Vetiver'],
    rationale: 'Montblanc\'s most seductive release — a dark, sweet vanilla-cardamom-apple EDP that sits confidently between Layton and La Nuit de L\'Homme. A criminally underrated date-night fragrance with strong projection in its opening hours.',
    intensity: 4,
    longevity: '6-8 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'montblanc-legend-red',
    name: 'Legend Red',
    house: 'Montblanc',
    price: 65,
    concentration: 'EDT',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Blood Orange', 'Grapefruit', 'Cardamom'],
    heartNotes: ['Cedar', 'Clary Sage', 'Juniper Berries'],
    baseNotes: ['Atlas Cedar', 'Mahogany', 'Tonka Bean'],
    rationale: 'A vibrant blood-orange and cardamom opening that dries down into a clean cedar-mahogany base reminiscent of Bleu de Chanel Parfum. An inoffensive, versatile daily driver that rewards generous application.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'montblanc-explorer-edp',
    name: 'Explorer',
    house: 'Montblanc',
    price: 80,
    concentration: 'EDP',
    imageUrl: '/bottles/montblanc-legend-red.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Pink Pepper'],
    heartNotes: ['Vetiver', 'Cacao', 'Patchouli'],
    baseNotes: ['Ambroxan', 'Leather', 'Sandalwood'],
    rationale: 'The fragrance community\'s go-to Aventus alternative — shares the same airy, ambroxan-driven DNA without the fruit and smoke. A clean, woody-leather EDP that works year-round and earns compliments without demanding attention.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'montblanc-explorer-platinum',
    name: 'Explorer Platinum',
    house: 'Montblanc',
    price: 85,
    concentration: 'EDP',
    family: ['Fresh', 'Woody'],
    occasion: ['Office', 'Everyday'],
    season: ['Spring', 'Summer'],
    topNotes: ['Violet Leaves', 'Grapefruit'],
    heartNotes: ['Clary Sage'],
    baseNotes: ['Cedarwood'],
    rationale: 'A pared-back, minimalist woody-aromatic built around a creamy violet-sage-cedar accord. Understated and clean — the kind of scent people notice without being able to name it. Perfect for the office or any setting where restraint is a virtue.',
    intensity: 2,
    longevity: '6-8 hrs',
    sillage: 'Soft',
    projection: 2,
  },
  {
    id: 'creed-original-vetiver',
    name: 'Original Vetiver',
    house: 'Creed',
    price: 335,
    concentration: 'EDP',
    imageUrl: '/bottles/montblanc-explorer-platinum.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Grapefruit', 'Bergamot', 'Lemon'],
    heartNotes: ['Vetiver', 'Geranium', 'Rose'],
    baseNotes: ['Sandalwood', 'White Musk', 'Ambergris'],
    rationale: 'A masterclass in refined simplicity — Creed takes the earthy, rooty character of vetiver and elevates it with a bright citrus opening and a whisper of rose, landing somewhere between a gentleman\'s study and a sun-drenched garden. Versatile enough for the office, distinguished enough for everything else.',
    intensity: 2,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'creed-silver-mountain-water',
    name: 'Silver Mountain Water',
    house: 'Creed',
    price: 345,
    concentration: 'EDP',
    imageUrl: '/bottles/creed-silver-mountain-water.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Mandarin'],
    heartNotes: ['Green Tea', 'Black Currant'],
    baseNotes: ['Galbanum', 'Musk', 'Sandalwood', 'Petitgrain'],
    rationale: 'Inspired by Olivier Creed\'s love of Alpine skiing, this 1995 classic captures high-altitude freshness like nothing else — bergamot and mandarin give way to a stunning green tea and blackcurrant heart over a musky sandalwood base. The definition of clean, sophisticated luxury.',
    intensity: 2,
    longevity: '6-8 hrs',
    sillage: 'Soft',
    projection: 2,
  },
  {
    id: 'initio-oud-for-greatness',
    name: 'Oud for Greatness',
    house: 'Initio Parfums Privés',
    price: 350,
    concentration: 'EDP',
    imageUrl: '/bottles/initio-oud-for-greatness.jpg',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Saffron', 'Nutmeg', 'Lavender'],
    heartNotes: ['Agarwood', 'Natural Oud Wood'],
    baseNotes: ['Patchouli', 'Musk'],
    rationale: 'Initio\'s crown jewel and one of the most respected western ouds ever made — saffron and nutmeg soften the oud\'s intensity into something bold yet approachable. Often described as a darker, earthier sibling to Baccarat Rouge 540. Nuclear longevity, commanding presence, and unmistakably masculine character. Not for the timid.',
    intensity: 5,
    longevity: '12+ hrs',
    sillage: 'Strong',
    projection: 5,
  },
  {
    id: 'initio-rehab',
    name: 'Rehab',
    house: 'Initio Parfums Privés',
    price: 430,
    concentration: 'EDP',
    imageUrl: '/bottles/initio-rehab.jpg',
    family: ['Woody', 'Fresh'],
    occasion: ['Office', 'Date Night', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Lavender', 'Black Pepper'],
    heartNotes: ['Cedarwood', 'Vetiver', 'Patchouli'],
    baseNotes: ['Sandalwood', 'Vanilla', 'Musk'],
    rationale: 'The Hedonist collection\'s most masculine entry — a niche-quality take on the Spicebomb DNA that elevates lavender, cedar, and patchouli over a creamy sandalwood-vanilla base. Barbershop sophistication done at the highest level. Versatile enough for the office yet interesting enough to wear out.',
    intensity: 3,
    longevity: '10-12 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'initio-blessed-baraka',
    name: 'Blessed Baraka',
    house: 'Initio Parfums Privés',
    price: 350,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal', 'Everyday'],
    season: ['Fall', 'Winter'],
    topNotes: ['White Flowers', 'Amber'],
    heartNotes: ['Sandalwood', 'Vanilla'],
    baseNotes: ['Musk', 'Amber'],
    rationale: 'One of the most underrated fragrances in the entire Initio line — a silky, balsamic amber-sandalwood that wears like warm skin in the cold. Reviewers often describe it as dark dried fruits and creamy vanilla powder; intimate rather than loud, yet with genuine beast-mode longevity. A winter signature for those who want presence without shouting.',
    intensity: 3,
    longevity: '10-12 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'initio-oud-for-happiness',
    name: 'Oud for Happiness',
    house: 'Initio Parfums Privés',
    price: 420,
    concentration: 'EDP',
    family: ['Woody', 'Amber'],
    occasion: ['Date Night', 'Everyday', 'Office'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Bergamot', 'Ginger'],
    heartNotes: ['Agarwood', 'Licorice', 'Cedar'],
    baseNotes: ['Vanilla', 'Herbal Notes', 'Musk'],
    rationale: 'The most approachable oud in the Initio catalog — ginger and bergamot keep the opening bright and energetic before the licorice-oud heart emerges, sweet and slightly herbal. Far less demanding than Oud for Greatness, yet still unmistakably niche in character. Community consensus: OFG is the evening king, OFH is the daytime oud you can actually wear year-round.',
    intensity: 3,
    longevity: '8-10 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'initio-atomic-rose',
    name: 'Atomic Rose',
    house: 'Initio Parfums Privés',
    price: 430,
    concentration: 'EDP',
    family: ['Floral', 'Amber'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Pink Pepper', 'Bergamot'],
    heartNotes: ['Bulgarian Rose', 'Turkish Rose', 'Egyptian Jasmine'],
    baseNotes: ['Madagascar Vanilla', 'Amber'],
    rationale: 'Initio\'s answer to Parfums de Marly Delina — a high-octane rose bomb built on dual Turkish and Bulgarian roses amplified by Hedione for maximum sensuality. The pink pepper and bergamot opening gives it an edge Delina lacks, and the vanilla-amber base anchors it into something seductive rather than purely feminine. Nuclear sillage; not subtle in any sense.',
    intensity: 4,
    longevity: '10-12 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'initio-absolute-aphrodisiac',
    name: 'Absolute Aphrodisiac',
    house: 'Initio Parfums Privés',
    price: 350,
    concentration: 'EDP',
    family: ['Amber', 'Woody'],
    occasion: ['Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['White Flowers', 'Amber'],
    heartNotes: ['Vanilla', 'Leather'],
    baseNotes: ['Musk', 'Castoreum', 'Amber'],
    rationale: 'The most primal fragrance in the Initio line — creamy vanilla and amber are cut through by castoreum, giving it a warm, skin-close animalic edge that earns its name. Reviewers call it chocolate vanilla with a masculine backbone. Wears intimate and close rather than projecting, which makes it devastating in the right context. A polarizing skin scent: people either can\'t stop sniffing their wrist or scrub it immediately.',
    intensity: 3,
    longevity: '8-10 hrs',
    sillage: 'Soft',
    projection: 2,
  },
  {
    id: 'initio-paragon',
    name: 'Paragon',
    house: 'Initio Parfums Privés',
    price: 430,
    concentration: 'EDP',
    family: ['Woody', 'Amber'],
    occasion: ['Everyday', 'Office', 'Date Night'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Lavender', 'Sage', 'Bergamot'],
    heartNotes: ['Palo Santo', 'Black Pepper'],
    baseNotes: ['Sandalwood', 'Agarwood'],
    rationale: 'Kai Cenat\'s signature and one of Initio\'s most versatile releases — palo santo and white sage create a warm, almost spiritual woody-aromatic that dries into a creamy sandalwood base. Masculine-leaning but approachable enough for any context. The kind of scent people notice without being able to identify.',
    intensity: 3,
    longevity: '10-12 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'dior-homme-edt',
    name: 'Dior Homme',
    house: 'Dior',
    price: 120,
    concentration: 'EDT',
    imageUrl: '/bottles/dior-homme-edt.jpg',
    family: ['Woody', 'Powdery'],
    occasion: ['Office', 'Evening'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Iris', 'Aldehydes'],
    heartNotes: ['Iris', 'Cacao', 'Lavender'],
    baseNotes: ['Vetiver', 'Virginian Cedar', 'Ambergris'],
    rationale: "The original Dior Homme EDT — a revolutionary iris-cocoa composition that redefined masculine fragrance. Lighter and crisper than the Intense, still the definitive powdery masculine.",
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'bleu-chanel-edt',
    name: 'Bleu de Chanel',
    house: 'Chanel',
    price: 155,
    concentration: 'EDT',
    imageUrl: '/bottles/bleu-chanel-edt.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Citrus', 'Mint', 'Pink Pepper'],
    heartNotes: ['Ginger', 'Nutmeg', 'Jasmine'],
    baseNotes: ['Incense', 'Vetiver', 'White Musk', 'Cedar'],
    rationale: "The entry point to the Bleu de Chanel universe — fresher and more citrus-forward than the EDP, with the same elegant DNA. A perennial best-seller and safe choice for any occasion.",
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'paco-invictus-edt',
    name: 'Invictus',
    house: 'Paco Rabanne',
    price: 75,
    concentration: 'EDT',
    imageUrl: '/bottles/paco-invictus-edt.jpg',
    family: ['Fresh', 'Aquatic'],
    occasion: ['Everyday', 'Sport'],
    season: ['Spring', 'Summer'],
    topNotes: ['Grapefruit', 'Sea Notes', 'Green Mandarin'],
    heartNotes: ['Bay Laurel', 'Hedione', 'Jasmine'],
    baseNotes: ['Oakmoss', 'Guaiac Wood', 'Ambergris'],
    rationale: "The original Invictus EDT — one of the best-selling fragrances in the world. A crowd-pleasing fresh aquatic built around hedione and grapefruit. The lighter, more versatile sibling to the EDP.",
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'jpg-scandal-pour-homme',
    name: 'Scandal Pour Homme',
    house: 'Jean Paul Gaultier',
    price: 85,
    concentration: 'EDT',
    imageUrl: '/bottles/jpg-scandal-pour-homme.jpg',
    family: ['Woody', 'Spicy'],
    occasion: ['Evening', 'Date'],
    season: ['Fall', 'Winter'],
    topNotes: ['Blood Orange', 'Aldehydes'],
    heartNotes: ['Vetiver', 'Sage'],
    baseNotes: ['Tonka Bean', 'Vanilla', 'Patchouli'],
    rationale: "JPG's answer to a modern masculine oriental — blood orange and aldehydes give way to a smoky vetiver-tonka heart. Distinctive and polarizing in the best way, a worthy complement to the Le Male line.",
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },

  {
    id: 'jpg-le-beau-edp',
    name: 'Le Beau',
    house: 'Jean Paul Gaultier',
    price: 110,
    concentration: 'EDP',
    imageUrl: '/bottles/jpg-le-beau-edp.jpg',
    family: ['Woody', 'Gourmand'],
    occasion: ['Evening', 'Date'],
    season: ['Fall', 'Winter'],
    topNotes: ['Coconut', 'Bergamot'],
    heartNotes: ['Vetiver', 'Iris'],
    baseNotes: ['Tonka Bean', 'Vanilla', 'Sandalwood'],
    rationale: "The darker, richer evolution of Le Beau EDT — the coconut warmth deepens into tonka and vanilla while vetiver adds sophistication. More of an evening fragrance than its lighter EDT sibling.",
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },

  {
    id: 'acqua-di-gio-edp',
    name: 'Acqua di Giò',
    house: 'Giorgio Armani',
    price: 110,
    concentration: 'EDP',
    imageUrl: '/bottles/acqua-di-gio-edp.jpg',
    family: ['Fresh', 'Aquatic'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Mandarin', 'Marine Accord'],
    heartNotes: ['Rosemary', 'Persimmon', 'Sage'],
    baseNotes: ['Patchouli', 'Cedarwood', 'Labdanum'],
    rationale: "A deeper, more complex take on the classic Acqua di Giò DNA — the EDP adds patchouli depth and richer base notes while retaining the signature aquatic freshness. More longevity and projection than the EDT.",
    intensity: 3,
    longevity: '7-9 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'ysl-y-edt',
    name: 'Y',
    house: 'YSL',
    price: 100,
    concentration: 'EDT',
    imageUrl: '/bottles/ysl-y-edt.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Bergamot', 'Ginger', 'Apple'],
    heartNotes: ['Geranium', 'Sage', 'Juniper'],
    baseNotes: ['Amberwood', 'Cedar', 'Vetiver'],
    rationale: "The lighter, fresher entry to the YSL Y family — bergamot and apple brightness over a clean woody base. More casual and approachable than Y Le Parfum, perfect for daytime and warmer months.",
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'hugo-boss-bottled-edp',
    name: 'Boss Bottled',
    house: 'Hugo Boss',
    price: 85,
    concentration: 'EDP',
    imageUrl: '/bottles/hugo-boss-bottled-edp.jpg',
    family: ['Woody', 'Spicy'],
    occasion: ['Office', 'Evening'],
    season: ['Fall', 'Winter'],
    topNotes: ['Apple', 'Bergamot', 'Plum'],
    heartNotes: ['Cinnamon', 'Mahogany', 'Geranium'],
    baseNotes: ['Sandalwood', 'Vanilla', 'Oakmoss', 'Vetiver'],
    rationale: "The EDP adds warmth and depth to the classic Boss Bottled formula — more cinnamon and vanilla richness with a spicier, more masculine edge. A step up in sophistication from the EDT for cooler weather.",
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  {
    id: 'dg-light-blue-edt',
    name: 'Light Blue',
    house: 'Dolce & Gabbana',
    price: 75,
    concentration: 'EDT',
    imageUrl: '/bottles/dg-light-blue-edt.jpg',
    family: ['Fresh', 'Citrus'],
    occasion: ['Everyday', 'Beach'],
    season: ['Spring', 'Summer'],
    topNotes: ['Grapefruit', 'Green Apple', 'Rosewood'],
    heartNotes: ['Rose', 'Bamboo', 'Jasmine'],
    baseNotes: ['Cedarwood', 'Amber', 'Musk'],
    rationale: "The original Light Blue for men — a crisp Mediterranean freshness built on citrus and apple. Lighter and more casual than the Eau Intense EDP, the quintessential summer holiday fragrance.",
    intensity: 2,
    longevity: '3-5 hrs',
    sillage: 'Light',
    projection: 2,
  },

  {
    id: 'polo-blue-edt',
    name: 'Polo Blue',
    house: 'Ralph Lauren',
    price: 70,
    concentration: 'EDT',
    imageUrl: '/bottles/polo-blue-edt.jpg',
    family: ['Fresh', 'Aquatic'],
    occasion: ['Everyday', 'Sport'],
    season: ['Spring', 'Summer'],
    topNotes: ['Melon', 'Cucumber', 'Basil'],
    heartNotes: ['Geranium', 'Sage', 'Rosewood'],
    baseNotes: ['Suede', 'Musk', 'Oakmoss'],
    rationale: "The lighter, airier sibling to the Polo Blue EDP — melon and cucumber freshness over a clean woody base. A reliable crowd-pleaser and staple of the Ralph Lauren lineup since 2003.",
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Light',
    projection: 2,
  },

  {
    id: 'guerlain-habit-rouge-edp',
    name: 'Habit Rouge',
    house: 'Guerlain',
    price: 130,
    concentration: 'EDP',
    imageUrl: '/bottles/guerlain-habit-rouge-edp.jpg',
    family: ['Oriental', 'Spicy'],
    occasion: ['Evening', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Citrus', 'Bergamot'],
    heartNotes: ['Spices', 'Rose', 'Sandalwood'],
    baseNotes: ['Vanilla', 'Labdanum', 'Benzoin', 'Tonka Bean'],
    rationale: "The EDP version of the legendary Habit Rouge adds depth and projection to the classic formula — richer vanillic warmth and spice with the same noble DNA. For evenings when you want maximum presence.",
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },

  {
    id: 'issey-miyake-leau-edp',
    name: "L'Eau d'Issey",
    house: 'Issey Miyake',
    price: 95,
    concentration: 'EDP',
    imageUrl: '/bottles/issey-miyake-leau-edp.jpg',
    family: ['Fresh', 'Woody'],
    occasion: ['Everyday', 'Office'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Yuzu', 'Mandarin', 'Bergamot'],
    heartNotes: ['Coriander', 'Sage', 'Nutmeg'],
    baseNotes: ['Vetiver', 'Cedarwood', 'Amber'],
    rationale: "A warmer, more substantial take on the iconic L'Eau d'Issey — the EDP deepens the aquatic-woody signature with added richness and longevity, more suitable for cooler months and evening wear.",
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  // ─── Giorgio Armani ───────────────────────────────────────────────────────
  {
    id: 'acqua-di-gio-edt',
    name: 'Acqua di Giò',
    house: 'Giorgio Armani',
    price: 85,
    concentration: 'EDT',
    imageUrl: '/bottles/acqua-di-gio-edt.jpg',
    family: ['Aquatic', 'Fresh'],
    occasion: ['Everyday', 'Office', 'Casual'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Neroli', 'Green Tangerine'],
    heartNotes: ['Jasmine', 'Calone', 'Persimmon'],
    baseNotes: ['Cedar', 'Patchouli', 'Musk'],
    rationale: "The world's best-selling men's fragrance for decades. Marine-fresh calone and jasmine over cedar and musk — the definitive summer cologne and the entry point for a generation of fragrance enthusiasts.",
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'armani-code-edt',
    name: 'Armani Code',
    house: 'Giorgio Armani',
    price: 90,
    concentration: 'EDT',
    imageUrl: '/bottles/armani-code-edt.jpg',
    family: ['Oriental', 'Woody'],
    occasion: ['Date Night', 'Evening', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Star Anise', 'Lemon'],
    heartNotes: ['Olive Blossom', 'Sage', 'Guaiac Wood'],
    baseNotes: ['Tonka Bean', 'Tobacco', 'Leather'],
    rationale: 'A seductive oriental-woody that defined the early 2000s evening fragrance category. Anise and olive blossom over a warm tobacco-tonka base — approachable, sophisticated, and reliable for evenings.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'armani-code-parfum',
    name: 'Armani Code',
    house: 'Giorgio Armani',
    price: 120,
    concentration: 'Parfum',
    imageUrl: '/bottles/armani-code-parfum.jpg',
    family: ['Oriental', 'Woody'],
    occasion: ['Date Night', 'Evening', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cardamom', 'Bergamot'],
    heartNotes: ['Apple', 'Cedarwood', 'Lavender'],
    baseNotes: ['Tonka Bean', 'Amber', 'Vanilla'],
    rationale: 'The Parfum concentration transforms Code into something richer and more enveloping — cardamom and apple add freshness while the tonka-vanilla base deepens considerably. One of the most wearable flankers in the Code family.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },

  // ─── Gucci ────────────────────────────────────────────────────────────────
  {
    id: 'gucci-guilty-edt',
    name: 'Guilty Pour Homme',
    house: 'Gucci',
    price: 85,
    concentration: 'EDT',
    imageUrl: '/bottles/gucci-guilty-edt.jpg',
    family: ['Oriental', 'Woody'],
    occasion: ['Date Night', 'Evening', 'Casual'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Lemon', 'Lavender', 'Pink Pepper'],
    heartNotes: ['Orange Flower', 'Cedar', 'Neroli'],
    baseNotes: ['Patchouli', 'Amber', 'Musk'],
    rationale: 'A smooth, lavender-led oriental with a patchouli-amber base. Guilty EDT sits in the sweet spot between fresh and warm — versatile enough for most occasions without demanding attention.',
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'gucci-guilty-absolute',
    name: 'Guilty Absolute Pour Homme',
    house: 'Gucci',
    price: 95,
    concentration: 'EDP',
    imageUrl: '/bottles/gucci-guilty-absolute.jpg',
    family: ['Woody', 'Leather'],
    occasion: ['Date Night', 'Evening', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Cypress', 'Fir'],
    heartNotes: ['Vetiver', 'Patchouli'],
    baseNotes: ['Leather', 'Woodsy Notes', 'Musk'],
    rationale: 'The darkest, most masculine entry in the Guilty line. Absolute strips away sweetness entirely — raw leather, wet patchouli, and cypress create something genuinely edgy and confident. Underrated.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },

  // ─── Givenchy ─────────────────────────────────────────────────────────────
  {
    id: 'givenchy-gentleman-edt',
    name: 'Gentleman',
    house: 'Givenchy',
    price: 85,
    concentration: 'EDT',
    imageUrl: '/bottles/givenchy-gentleman-edt.jpg',
    family: ['Aromatic', 'Woody'],
    occasion: ['Everyday', 'Office', 'Casual'],
    season: ['Spring', 'Fall'],
    topNotes: ['Bergamot', 'Cardamom', 'Pear'],
    heartNotes: ['Iris', 'Geranium', 'Patchouli'],
    baseNotes: ['Leather', 'Vetiver', 'Amber'],
    rationale: 'The modern Gentleman EDT balances iris refinement with warm patchouli and leather — approachable, polished, and genuinely versatile. A strong everyday option that punches above its price point.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'givenchy-xeryus',
    name: 'Xeryus Rouge',
    house: 'Givenchy',
    price: 65,
    concentration: 'EDT',
    imageUrl: '/bottles/givenchy-xeryus-rouge.jpg',
    family: ['Oriental', 'Woody'],
    occasion: ['Evening', 'Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Coriander', 'Tagete', 'Cardamom'],
    heartNotes: ['Carnation', 'Geranium', 'Cedar'],
    baseNotes: ['Amber', 'Sandalwood', 'Musk'],
    rationale: 'An underappreciated oriental-woody from the 90s that rewards those who seek it out. Spicy, warm, and distinctive — Xeryus Rouge has outlasted countless trendier releases.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  // ─── Bvlgari ──────────────────────────────────────────────────────────────
  {
    id: 'bvlgari-pour-homme-soir',
    name: 'Pour Homme Soir',
    house: 'Bvlgari',
    price: 80,
    concentration: 'EDT',
    imageUrl: '/bottles/bvlgari-pour-homme-soir.jpg',
    family: ['Woody', 'Aromatic'],
    occasion: ['Evening', 'Date Night', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Elemi', 'Petitgrain', 'Bergamot'],
    heartNotes: ['Geranium', 'Sage', 'Juniper'],
    baseNotes: ['Sandalwood', 'Vetiver', 'Musk'],
    rationale: 'A sophisticated aromatic-woody evening fragrance from Bvlgari. Slightly smoky and resinous, Pour Homme Soir is polished without being stiff — ideal for formal occasions and cooler evenings.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'bvlgari-aqva',
    name: 'Aqva Pour Homme',
    house: 'Bvlgari',
    price: 75,
    concentration: 'EDT',
    imageUrl: '/bottles/bvlgari-aqva.jpg',
    family: ['Aquatic', 'Fresh'],
    occasion: ['Everyday', 'Casual', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Posidonia', 'Marine Accord', 'Citrus'],
    heartNotes: ['Ginger', 'Petitgrain', 'Cyclamen'],
    baseNotes: ['Musky Wood', 'Amber', 'Sandal'],
    rationale: "A refined aquatic with a mineral edge — Bvlgari's take on the marine genre adds Italian elegance to what could be a generic category. Crisp, clean, and well-constructed for summer and sport.",
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'bvlgari-omnia',
    name: 'Omnia Crystalline',
    house: 'Bvlgari',
    price: 70,
    concentration: 'EDT',
    imageUrl: '/bottles/bvlgari-omnia-crystalline.jpg',
    family: ['Fresh', 'Floral'],
    occasion: ['Everyday', 'Office', 'Casual'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bamboo', 'Lotus', 'Cassia'],
    heartNotes: ['White Tuberose', 'Balsa Wood'],
    baseNotes: ['Musk', 'Sandalwood'],
    rationale: 'A luminous, transparent floral-fresh that defined understated elegance for a generation. Omnia Crystalline is clean, light, and effortlessly wearable — the definition of quiet luxury in a bottle.',
    intensity: 2,
    longevity: '4-5 hrs',
    sillage: 'Light',
    projection: 2,
  },

  // ─── Burberry ─────────────────────────────────────────────────────────────
  {
    id: 'burberry-hero-edp',
    name: 'Hero',
    house: 'Burberry',
    price: 95,
    concentration: 'EDP',
    imageUrl: '/bottles/burberry-hero-edp.jpg',
    family: ['Woody', 'Aromatic'],
    occasion: ['Everyday', 'Office', 'Casual'],
    season: ['Spring', 'Fall'],
    topNotes: ['Juniper Berry', 'Black Pepper'],
    heartNotes: ['Vetiver', 'Cedar'],
    baseNotes: ['Oakwood', 'Musk'],
    rationale: "Burberry's most acclaimed modern masculine — a clean, mineral-woody built around a distinctive oakwood accord. Hero EDP is effortlessly versatile and receives consistent compliments across all contexts.",
    intensity: 3,
    longevity: '7-9 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'burberry-mr-burberry-edt',
    name: 'Mr. Burberry',
    house: 'Burberry',
    price: 80,
    concentration: 'EDT',
    imageUrl: '/bottles/burberry-mr-burberry.jpg',
    family: ['Aromatic', 'Woody'],
    occasion: ['Everyday', 'Office', 'Casual'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Grapefruit', 'Cardamom', 'Tarragon'],
    heartNotes: ['Birch', 'Heather', 'Guaiac Wood'],
    baseNotes: ['Sandalwood', 'Vetiver', 'Oakmoss'],
    rationale: "An elegant British aromatic-woody inspired by Burberry's heritage. Cardamom and grapefruit open cleanly before warm birch and sandalwood take over — polished, reliable, and broader than it first appears.",
    intensity: 3,
    longevity: '5-7 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'burberry-brit-edt',
    name: 'Brit for Men',
    house: 'Burberry',
    price: 70,
    concentration: 'EDT',
    imageUrl: '/bottles/burberry-brit.jpg',
    family: ['Aromatic', 'Fougère'],
    occasion: ['Everyday', 'Casual', 'Office'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Ginger', 'Lemon', 'Basil'],
    heartNotes: ['Cedar', 'Nutmeg', 'Geranium'],
    baseNotes: ['Tonka Bean', 'Amber', 'Musk'],
    rationale: "A classic British fougère-adjacent with a warm spicy edge. Brit's ginger-tonka combination is approachable and broadly appealing — an accessible entry point to Burberry's masculine range.",
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Light',
    projection: 2,
  },

  // ─── Carolina Herrera ─────────────────────────────────────────────────────
  {
    id: 'ch-212-men-edt',
    name: '212 Men',
    house: 'Carolina Herrera',
    price: 75,
    concentration: 'EDT',
    imageUrl: '/bottles/ch-212-men.jpg',
    family: ['Fresh', 'Aromatic'],
    occasion: ['Everyday', 'Casual', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Bergamot', 'Cardamom', 'Cabreuva'],
    heartNotes: ['Sage', 'Geranium', 'Sandalwood'],
    baseNotes: ['Oakmoss', 'Amber', 'Musk'],
    rationale: 'A laid-back fresh-aromatic built for New York living. 212 Men is clean, contemporary, and easy to wear — the kind of fragrance that works equally well at the office and on a Sunday afternoon.',
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Moderate',
    projection: 2,
  },
  {
    id: 'ch-bad-boy-edt',
    name: 'Bad Boy',
    house: 'Carolina Herrera',
    price: 90,
    concentration: 'EDT',
    imageUrl: '/bottles/ch-bad-boy.jpg',
    family: ['Woody', 'Aromatic'],
    occasion: ['Date Night', 'Evening', 'Casual'],
    season: ['Fall', 'Winter'],
    topNotes: ['Bergamot', 'Pepper', 'Elemi'],
    heartNotes: ['Sage', 'Cacao', 'Cedarwood'],
    baseNotes: ['Vetiver', 'Tonka Bean', 'Labdanum'],
    rationale: 'A dark, spicy aromatic-woody that leans into its seductive edge. Bad Boy EDT pairs sage and pepper with a rich cacao-vetiver base — more refined than its name suggests, and a strong performer at night.',
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },
  {
    id: 'ch-good-girl-blush',
    name: 'Good Girl Blush',
    house: 'Carolina Herrera',
    price: 110,
    concentration: 'EDP',
    imageUrl: '/bottles/ch-good-girl-blush.jpg',
    family: ['Floral', 'Gourmand'],
    occasion: ['Date Night', 'Evening', 'Casual'],
    season: ['Spring', 'Fall', 'Winter'],
    topNotes: ['Rose', 'Peony', 'Grapefruit'],
    heartNotes: ['Jasmine', 'Tuberose'],
    baseNotes: ['Vanilla', 'Tonka Bean', 'Musk'],
    rationale: 'A softer, more romantic interpretation of the Good Girl DNA. Rose and peony lead over a warm tonka-vanilla base — feminine without being cloying, and broadly compliment-generating across seasons.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },

  // ─── Viktor & Rolf ────────────────────────────────────────────────────────
  {
    id: 'spicebomb-edt',
    name: 'Spicebomb',
    house: 'Viktor & Rolf',
    price: 85,
    concentration: 'EDT',
    imageUrl: '/bottles/spicebomb-edt.jpg',
    family: ['Spicy', 'Woody'],
    occasion: ['Everyday', 'Date Night', 'Office'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Bergamot', 'Grapefruit', 'Pink Pepper'],
    heartNotes: ['Cinnamon', 'Saffron', 'Tobacco'],
    baseNotes: ['Leather', 'Vetiver', 'Chili'],
    rationale: 'The original grenade-bottle classic that launched a spicy revolution. Spicebomb EDT balances fresh citrus with a spicy tobacco-leather core — versatile enough for daily wear, with more bite than most office-safe fragrances.',
    intensity: 3,
    longevity: '6-8 hrs',
    sillage: 'Moderate',
    projection: 3,
  },
  {
    id: 'bonbon-edp',
    name: 'Flowerbomb',
    house: 'Viktor & Rolf',
    price: 130,
    concentration: 'EDP',
    imageUrl: '/bottles/vr-flowerbomb.jpg',
    family: ['Floral', 'Gourmand'],
    occasion: ['Date Night', 'Evening', 'Casual'],
    season: ['Fall', 'Winter', 'Spring'],
    topNotes: ['Bergamot', 'Tea', 'Osmanthus'],
    heartNotes: ['Jasmine', 'Rose', 'Freesia', 'Orchid'],
    baseNotes: ['Patchouli', 'Musk', 'Amber'],
    rationale: 'One of the most successful floral-oriental launches of the 2000s. Flowerbomb is an explosion of jasmine, rose, and patchouli held together by a sweet amber base — warm, enveloping, and reliably compliment-generating.',
    intensity: 4,
    longevity: '8-10 hrs',
    sillage: 'Strong',
    projection: 4,
  },

  // ─── Jo Malone ────────────────────────────────────────────────────────────
  {
    id: 'jo-malone-peony-blush',
    name: 'Peony & Blush Suede',
    house: 'Jo Malone',
    price: 155,
    concentration: 'Cologne',
    imageUrl: '/bottles/jo-malone-peony.jpg',
    family: ['Floral', 'Woody'],
    occasion: ['Everyday', 'Date Night', 'Casual'],
    season: ['Spring', 'Summer', 'Fall'],
    topNotes: ['Red Apple', 'Peony'],
    heartNotes: ['Jasmine', 'Rose'],
    baseNotes: ['Suede', 'Musk'],
    rationale: "Jo Malone's most popular cologne — a soft, powdery floral with a suede-smooth drydown. Peony & Blush Suede is elegant, easy to wear, and pairs beautifully with other colognes from the range.",
    intensity: 2,
    longevity: '4-6 hrs',
    sillage: 'Light',
    projection: 2,
  },
  {
    id: 'jo-malone-lime-basil',
    name: 'Lime Basil & Mandarin',
    house: 'Jo Malone',
    price: 140,
    concentration: 'Cologne',
    imageUrl: '/bottles/jo-malone-lime-basil.jpg',
    family: ['Fresh', 'Aromatic'],
    occasion: ['Everyday', 'Casual', 'Office'],
    season: ['Spring', 'Summer'],
    topNotes: ['Lime', 'Mandarin'],
    heartNotes: ['Basil', 'White Thyme'],
    baseNotes: ['Patchouli', 'Amber', 'Cedar'],
    rationale: "The fragrance that put Jo Malone on the map — an iconic aromatic-citrus that smells simultaneously fresh and sophisticated. Lime Basil & Mandarin is the benchmark for clean British cologne.",
    intensity: 2,
    longevity: '3-5 hrs',
    sillage: 'Light',
    projection: 2,
  },
  {
    id: 'jo-malone-velvet-rose',
    name: 'Velvet Rose & Oud',
    house: 'Jo Malone',
    price: 200,
    concentration: 'Cologne Intense',
    imageUrl: '/bottles/jo-malone-velvet-rose-oud.jpg',
    family: ['Floral', 'Woody'],
    occasion: ['Date Night', 'Evening', 'Formal'],
    season: ['Fall', 'Winter'],
    topNotes: ['Rose'],
    heartNotes: ['Rose', 'Oud'],
    baseNotes: ['Guaiac Wood', 'Patchouli', 'Musk'],
    rationale: "From Jo Malone's Cologne Intense line — a darker, richer take pairing rose with oud and guaiac wood. Velvet Rose & Oud is the house at its most opulent, suited to evenings and cooler months.",
    intensity: 4,
    longevity: '7-9 hrs',
    sillage: 'Strong',
    projection: 4,
  },

]
