import next from 'eslint-config-next'

// Named rather than an inline anonymous array: eslint-plugin-import's
// no-anonymous-default-export rule (enabled by eslint-config-next) flags
// this file otherwise, which is a silly way to start a lint run.
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      // Vendored shadcn/ui components. Generated by the CLI and re-generated
      // when components are added, so violations here are not ours to fix.
      // Removing this line adds 3 errors and 1 warning as of this commit.
      'components/ui/**',
    ],
  },
  ...next,
]

export default config
