export function Footer() {
  return (
    <footer className="border-t border-border bg-background">
      <div className="mx-auto max-w-[1200px] px-6 py-12 lg:px-8">
        <div className="flex flex-col items-center gap-4 text-center">
          <span className="font-serif text-lg text-cream/60">
            The Art & Science of Men&apos;s Fragrance
          </span>
          <div className="h-px w-12 bg-gold/30" />
          <p className="max-w-md text-xs text-cream-muted/40 leading-relaxed">
            A comprehensive interactive guide to the world of men&apos;s fragrance
            subculture, covering terminology, classification, popular scents,
            community culture, and practical recommendations.
          </p>
          <p className="mt-4 text-[10px] text-cream-muted/30 uppercase tracking-widest">
            Generated by Superagent.
          </p>
        </div>
      </div>
    </footer>
  )
}
